In [1]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'
import re
import os

In [2]:
#Import the facebook_dataset:

fb_dset = pd.read_csv(r"C:\Users\crocs\OneDrive - Universidade de Lisboa\Ambiente de Trabalho\Gonçalo\College&Courses\Data Analytics- IronHack\Course Data Analytics\Projects\FinalProject\Mycode\database\final_200_250.csv")
#fb_dset2 = pd.read_csv(r"C:\Users\crocs\OneDrive - Universidade de Lisboa\Ambiente de Trabalho\Gonçalo\College&Courses\Data Analytics- IronHack\Course Data Analytics\Projects\FinalProject\Mycode\database\final_050.csv")
fb_dset.head(5)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Name,Compl_Name,place_id,types,International Phone Number,Website,...,fb_phone_num,email,following_fb,website_fb,company_address,company_phone_num,company_website,company_workers,sales_volume,extra_column
0,0,200,200,200,Farmácia Luciano Cordeiro,NaN,ChIJKy4zd50zGQ0RGi98bEfm9s4,"['pharmacy', 'health', 'point_of_interest', 's...",+351 21 315 6381,https://www.farmaciasportuguesas.pt/catalogo/f...,...,NaN,NaN,NaN,NaN,"1150-213, LISBOA Portugal *Address and contact...",4,"$558,113",2005,NaN,NaN
1,1,201,201,201,Farmácia Europa,NaN,ChIJd5QWJZIzGQ0RhWYebwypVG4,"['pharmacy', 'health', 'point_of_interest', 's...",+351 21 814 3880,https://www.facebook.com/farmaciaeuropalisboa/,...,"[('', '', '21 814 3880', '', '21 814 3880')]","['farmaciaeuropalx@gmail.com', 'farmaciaeuropa...",['disto722 pessoas'],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,202,202,202,Farmácia Colonial,NaN,ChIJt999E5AzGQ0Rygswn2EAm-Y,"['pharmacy', 'health', 'point_of_interest', 's...",+351 21 814 1122,https://www.farmaciasportuguesas.pt/catalogo/f...,...,"[('', '', '729079999', '999', ''), ('', '', '2...","['farmacia.colonial@freemacia.pt', 'farmacia.c...",['disto471 pessoas'],['http://www.freemacia.pt'],"AVENIDA JOÃO PAULO II, 52C 2970-868, SESIMBRA ...",+351-913791690,14,$3.25 million,2006,NaN
3,3,203,203,203,Farmácia do Monte,NaN,ChIJnXmbuo4zGQ0RRKU2euh5Y_w,"['pharmacy', 'health', 'point_of_interest', 's...",+351 21 882 0790,https://farmacia-monte.negocio.site/,...,"[('', '', '725495505', '505', ''), ('', '', '7...","['farmaciadomonte.lisboa@gmail.com', 'farmacia...",['disto568 pessoas'],[],"5110-166, ARMAMAR Portugal *Address and contac...",1,"$44,000",2010,NaN,NaN
4,4,204,204,204,Farmácia Santa Apolónia,NaN,ChIJd0wPTXU0GQ0R6YQXI3rYTvA,"['pharmacy', 'health', 'point_of_interest', 's...",+351 21 886 2376,https://www.farmaciasportuguesas.pt/catalogo/f...,...,"[('', '', '717827748', '748', ''), ('', '', '1...","['farmacia.stapolonia@gmail.com', 'farmacia.st...",['disto1129 pessoas'],[],NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Treating Email column:

fb_dset["email"].fillna(value=0,  inplace=True)
fb_dset["email"].astype(object)
for i in range(len(fb_dset)):
    if fb_dset["email"].iloc[i] == '[]':
        fb_dset["email"].iloc[i] = 0
    else:
        fb_dset["email"].iloc[i] =fb_dset["email"].iloc[i]
        
for i in range(len(fb_dset)):
    if fb_dset["email"].iloc[i] != 0 :
        a=re.findall("[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,3}", fb_dset["email"].iloc[i])
        fb_dset["email"].iloc[i] = a[0]
    
    else:
        fb_dset["email"].iloc[i] = fb_dset["email"].iloc[i]

In [6]:
fb_dset["email"].head(4)

0                                   0
1          farmaciaeuropalx@gmail.com
2      farmacia.colonial@freemacia.pt
3    farmaciadomonte.lisboa@gmail.com
Name: email, dtype: object

In [7]:
#Treating Phone number column:

fb_dset["fb_phone_num"].fillna(value=0,  inplace=True)
fb_dset["fb_phone_num"].astype(object)
for i in range(len(fb_dset)):
    if fb_dset["fb_phone_num"].iloc[i] == '[]':
        fb_dset["fb_phone_num"].iloc[i] = 0
    else:
        fb_dset["fb_phone_num"].iloc[i] =fb_dset["fb_phone_num"].iloc[i]
        
for i in range(len(fb_dset)):
    if fb_dset["fb_phone_num"].iloc[i] != 0 :
        b = re.findall("((\d{3} ?){3}|(\d{2} ?\d{3} ?\d{4}?))",fb_dset["fb_phone_num"].iloc[i] )
        fb_dset["fb_phone_num"].iloc[i] = b[0][0].replace(" ","")
    
    else:
        fb_dset["fb_phone_num"].iloc[i] = fb_dset["fb_phone_num"].iloc[i]

In [8]:
#Deleting numbers not starting in 9 or 2:

for i in range(len(fb_dset)):
    if fb_dset["fb_phone_num"].iloc[i] != 0 :
        if (fb_dset["fb_phone_num"].iloc[i][0] =="9") | (fb_dset["fb_phone_num"].iloc[i][0] =="2" ) :
            fb_dset["fb_phone_num"].iloc[i] = fb_dset["fb_phone_num"].iloc[i] 
        
        else:
            fb_dset["fb_phone_num"].iloc[i] = 0
        
    else:
        fb_dset["fb_phone_num"].iloc[i] = 0
        
fb_dset["fb_phone_num"].head(10)

0            0
1    218143880
2            0
3            0
4            0
5            0
6            0
7    218824924
8    213964238
9            0
Name: fb_phone_num, dtype: object

In [9]:
#Treating Website column, fill with 0 and replace empty lists:

fb_dset["website_fb"].fillna(value=0,  inplace=True)
fb_dset["website_fb"].astype(object)
for i in range(len(fb_dset)):
    if fb_dset["website_fb"].iloc[i] == '[]':
        fb_dset["website_fb"].iloc[i] = 0
    else:
        fb_dset["website_fb"].iloc[i] =fb_dset["website_fb"].iloc[i]

In [10]:
#Treating Website column, replace unwanted [] and '':

for i in range(len(fb_dset)):
    if fb_dset["website_fb"].iloc[i] != 0 :

        fb_dset["website_fb"].iloc[i] = fb_dset["website_fb"].iloc[i].replace("['","").replace("']","")
                
    else:
        fb_dset["website_fb"].iloc[i] = 0

In [ ]:
fb_dset.tail(3)

In [11]:
fb_dset["company_phone_num"].fillna(value=" ",  inplace=True)

fb_dset["company_website"].fillna(value=" ",  inplace=True)

fb_dset["company_workers"].fillna(value=" ",  inplace=True)

fb_dset["sales_volume"].fillna(value=" ",  inplace=True)

In [12]:

fb_dset['extra_column'] = fb_dset[['company_phone_num', 'company_website', "company_workers","sales_volume"]].agg('_'.join, axis=1)

In [13]:
fb_dset.drop(columns = {"Unnamed: 0","Unnamed: 0.1","Unnamed: 0.1.1","Unnamed: 0.1.1.1","Compl_Name","company_website","company_workers","sales_volume"}, inplace = True)
fb_dset.drop(columns = {"mandatario","morada","codigo_postal","company_address"}, inplace = True)

In [ ]:
fb_dset["num_workers"] = np.nan 
for i in range(len(fb_dset)):
    fb_dset["num_workers"].iloc[i] = re.findall("_.*_\$",fb_dset["extra_column"].iloc[i] )
    if fb_dset["num_workers"].iloc[i] == []:
        fb_dset["num_workers"].iloc[i] = re.findall(".*_\$",fb_dset["extra_column"].iloc[i] )
    else:
        fb_dset["num_workers"].iloc[i] = fb_dset["num_workers"].iloc[i]
    
fb_dset["num_workers"]

In [14]:
##Arrange num_workers column:

fb_dset["num_workers"] = np.nan

for i in range(len(fb_dset)):
    if fb_dset["extra_column"].iloc[i] != ' _ _ _ '  :
#         for element in fb_dset["num_workers"].iloc[i]:

        fb_dset["num_workers"].iloc[i] =  fb_dset["extra_column"].iloc[i].replace("www","").replace(",","")
        fb_dset["num_workers"].iloc[i] = re.findall("_?\w+_\$",fb_dset["extra_column"].iloc[i] )

    else:
        fb_dset["num_workers"].iloc[i] = 0


for i in range(len(fb_dset)):
    if fb_dset["num_workers"].iloc[i] == 0  :
        fb_dset["num_workers"].iloc[i] = []

    else :
        fb_dset["num_workers"].iloc[i] = fb_dset["num_workers"].iloc[i]
        
for i in range(len(fb_dset)):
    if fb_dset["num_workers"].iloc[i] != []:
        for element in fb_dset["num_workers"].iloc[i]: 
            fb_dset["num_workers"].iloc[i] = re.findall("\d{1,6}_\$",element)
        
    else:
        fb_dset["num_workers"].iloc[i] = fb_dset["num_workers"].iloc[i]
           
            
#             #re.findall("\d{1,6}_\$",fb_dset["num_workers"].iloc[1][0])
            
for i in range(len(fb_dset)):
    if fb_dset["num_workers"].iloc[i] != []:
        
        for element in fb_dset["num_workers"].iloc[i]:
            fb_dset["num_workers"].iloc[i] = element.replace("_$","")
            
    else:
        fb_dset["num_workers"].iloc[i] = 0
fb_dset["num_workers"]

0       4
1       0
2      14
3       1
4       0
5       0
6      12
7       5
8       3
9       3
10      9
11      8
12     11
13      0
14      7
15      9
16      0
17     16
18     20
19     10
20      0
21      0
22    637
23      0
24      0
25      0
26     11
27     11
28      0
29     11
30      8
31      9
32      0
33      9
34      0
35      8
36      6
37     19
38      7
39      7
40      0
41      7
42     15
43      0
44      0
45      0
46      0
47      0
48    173
49      0
Name: num_workers, dtype: object

In [15]:
# ##Arrange num_workers column:

fb_dset["sales_vol"] = np.nan

for i in range(len(fb_dset)):
    if fb_dset["extra_column"].iloc[i] != ' _ _ _ '  :
#         for element in fb_dset["num_workers"].iloc[i]:

        fb_dset["sales_vol"].iloc[i] =  fb_dset["extra_column"].iloc[i].replace("www","").replace(",","").replace(".","").replace("million","0000").replace(" ","").replace("billion","0000")
        fb_dset["sales_vol"].iloc[i] = re.findall("_\$.*_?",fb_dset["sales_vol"].iloc[i] )

    else:
#         fb_dset["sales_vol"].iloc[i] = 0
#         fb_dset["sales_vol"].iloc[i] = int(fb_dset["sales_vol"].iloc[i]
        fb_dset["sales_vol"].iloc[i] = 0



for i in range(len(fb_dset)):
    if fb_dset["sales_vol"].iloc[i] != 0:
        for element in fb_dset["sales_vol"].iloc[i]: 
            fb_dset["sales_vol"].iloc[i] = re.findall("_\$.{1,16}_?",element)
        
    else:
        fb_dset["sales_vol"].iloc[i] = fb_dset["sales_vol"].iloc[i]


    
            
for i in range(len(fb_dset)):
    if fb_dset["sales_vol"].iloc[i] == [] :
        fb_dset["sales_vol"].iloc[i]= 0
    
    elif fb_dset["sales_vol"].iloc[i] != 0:
        for element in fb_dset["sales_vol"].iloc[i]:
            fb_dset["sales_vol"].iloc[i]= element + "_"  

    else:
        fb_dset["sales_vol"].iloc[i]= 0

        
for i in range(len(fb_dset)):
    if fb_dset["sales_vol"].iloc[i] != 0:

        fb_dset["sales_vol"].iloc[i] = re.findall("_\$\d+_",fb_dset["sales_vol"].iloc[i])
        for element in fb_dset["sales_vol"].iloc[i]:
            fb_dset["sales_vol"].iloc[i]= element 
        fb_dset["sales_vol"].iloc[i] = fb_dset["sales_vol"].iloc[i].replace("_","").replace("$","")
    else:
        fb_dset["sales_vol"].iloc[i] = fb_dset["sales_vol"].iloc[i]
           
fb_dset["num_workers"] =fb_dset["num_workers"].astype(int)
fb_dset["sales_vol"] = fb_dset["sales_vol"].astype(int)
            

fb_dset["sales_vol"]

0        558113
1             0
2       3250000
3         44000
4             0
5             0
6       1610000
7        819216
8        644727
9        871921
10      1700000
11      1560000
12      2170000
13            0
14      1430000
15      1250000
16            0
17      2520000
18      1690000
19      1510000
20            0
21            0
22    296020000
23            0
24            0
25            0
26      3250000
27      2170000
28            0
29      2170000
30      1360000
31      2080000
32            0
33      2080000
34            0
35      1360000
36       962379
37       652388
38      1240000
39      1430000
40            0
41      1430000
42      3600000
43            0
44            0
45            0
46            0
47            0
48      2420000
49            0
Name: sales_vol, dtype: int32

In [16]:
##Save dataframe:

fb_dset.to_csv(r"C:\Users\crocs\OneDrive - Universidade de Lisboa\Ambiente de Trabalho\Gonçalo\College&Courses\Data Analytics- IronHack\Course Data Analytics\Projects\FinalProject\Mycode\database\last\last_200_250.csv")

In [ ]:


#Columns to get to the Algorithm:

    #Rating , user_rating_total , got website ,got facebook , following_fb , num_workers , sales_vol